//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Dob { get; set; }
        public string FatherName { get; set; }
        public string ContactNo { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
    }
}
